// ATTORNEY REVIEW REQUIRED — these templates were authored in-house as
// complete operational documents. They are live and signable, but a licensed
// Michigan attorney should review them; record the review here when done.

const GOVERNING_LAW = 'This document is governed by the laws of the State of Michigan, United States, without regard to conflict-of-law principles. The state and federal courts located in Michigan have exclusive jurisdiction over any dispute arising out of or relating to this document, and each party consents to venue in those courts; either party may instead bring a qualifying claim in small claims court. If any provision is held unenforceable, the remaining provisions continue in full force, and the unenforceable provision is reformed to the minimum extent necessary to make it enforceable.';

export const LEGAL_TEMPLATE_SEED = [
  {
    template_key: 'platform_terms_privacy_ack',
    role: 'athlete',
    version: '2.1.0',
    title: 'Platform Terms, Privacy, and Electronic Records Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. ACCEPTANCE OF TERMS. By creating an account, signing this acknowledgement, or using any LevelCoach Training service, I agree to be bound by the then-current LevelCoach Training Terms of Service and Privacy Policy, each of which is incorporated into this acknowledgement by reference. If I do not agree, I must not use the services. I confirm that the information I provide during registration and at all times thereafter is accurate, current, and complete, and that I will promptly update it when it changes.',
      '',
      '2. DESCRIPTION OF SERVICES. LevelCoach Training is a multi-sport training marketplace and operations platform that connects athletes, parents and guardians, independent coaches, and training organizations across team sports, individual sports, and athletic performance disciplines, including but not limited to soccer, basketball, football, baseball, softball, volleyball, tennis, lacrosse, hockey, golf, track and field, swimming, and speed, agility, strength, and general performance training. LevelCoach provides scheduling, booking, messaging, payment processing, training records, and related tools. LevelCoach is not itself a provider of coaching services and does not employ the coaches listed on the platform.',
      '',
      '3. ELIGIBILITY AND ACCOUNTS. I represent that I am at least eighteen (18) years of age and have legal capacity to enter this agreement, or that I am at least thirteen (13) years of age and use the platform under the supervision and consent of my parent or legal guardian as required by platform policy. Children under thirteen (13) may not register their own accounts. Minor athletes are represented on the platform through a parent or legal guardian account, and LevelCoach collects personal information relating to children under thirteen (13) only with verifiable parental consent, consistent with the Children\'s Online Privacy Protection Act (COPPA). I am responsible for maintaining the confidentiality of my login credentials and for all activity under my account.',
      '',
      '4. ELECTRONIC RECORDS AND SIGNATURES. I consent to the use of electronic records, electronic delivery of disclosures, and electronic signatures for all account, booking, payment, safety, messaging, legal, and training-related documents, consistent with the federal E-SIGN Act and applicable Michigan electronic transactions law. I understand that I may request paper copies of signed documents and may withdraw this consent by closing my account, in which case I may be unable to continue using the services.',
      '',
      '5. PRIVACY AND DATA PRACTICES. I acknowledge the LevelCoach Privacy Policy, which describes the categories of personal information collected (including profile, scheduling, payment, communication, and training-progress data), the purposes of processing, retention practices, and the limited circumstances in which information is shared with coaches, organizations, guardians, payment processors, and service providers. LevelCoach does not sell personal information. Health-related information provided for safety purposes is used only for safety and emergency-response purposes.',
      '',
      '6. ACCEPTABLE USE. I agree not to misuse the services, including by attempting to access another user\'s data, circumventing platform safety or payment controls, harvesting contact information, posting unlawful or harmful content, or soliciting off-platform transactions in violation of platform policy. LevelCoach may suspend or terminate accounts that violate these terms or that present a safety risk to other users.',
      '',
      '7. THIRD-PARTY SERVICES. Payments are processed by Stripe, Inc. and are subject to Stripe\'s terms and privacy practices. Other integrated service providers are identified in the Privacy Policy. LevelCoach is not responsible for third-party services beyond the responsibilities stated in the Terms of Service.',
      '',
      '8. MODIFICATIONS. LevelCoach may update the Terms of Service, the Privacy Policy, and required legal documents from time to time. Material changes will be communicated through the platform, and continued use after the effective date of a change constitutes acceptance. Certain changes may require a new signature before further booking or participation.',
      '',
      '9. DISCLAIMERS AND LIMITATION OF LIABILITY. Except as expressly stated in the Terms of Service, the services are provided on an "as is" and "as available" basis. To the maximum extent permitted by law, LevelCoach\'s aggregate liability arising out of or relating to the services is limited as described in the Terms of Service. Nothing in this acknowledgement limits liability that cannot be limited under applicable law.',
      '',
      '10. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'athlete_participation_waiver',
    role: 'athlete',
    version: '2.1.0',
    title: 'Athlete Participation, Assumption of Risk, Waiver, Release, and Indemnification',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. ACKNOWLEDGEMENT OF INHERENT RISK. I understand that participation in athletic training of any kind — including team sports such as soccer, basketball, football, baseball, softball, volleyball, lacrosse, and hockey; individual sports such as tennis, golf, track and field, and swimming; and performance disciplines such as speed, agility, strength, and conditioning training — involves inherent and unavoidable risks. These risks include, without limitation, physical exertion, collisions with other participants, contact with balls, sticks, bats, racquets, pucks, weights, and other equipment, contact with playing surfaces, water-related risks, weather and environmental conditions, travel to and from training locations, and the risk of minor injury, serious injury, permanent disability, or death.',
      '',
      '2. VOLUNTARY PARTICIPATION. My participation in training sessions booked through LevelCoach Training is entirely voluntary. I have had the opportunity to ask questions about the nature of the activities, and I choose to participate with full knowledge of the risks involved.',
      '',
      '3. MEDICAL FITNESS REPRESENTATION. I represent that I am physically and medically able to participate in the training activities I book, or that I will consult a qualified medical professional before participating. I agree to inform my coach before each session of any injury, illness, or condition that could affect my safe participation, and to stop participating and notify my coach immediately if I experience pain, dizziness, difficulty breathing, or other warning signs during a session.',
      '',
      '4. ASSUMPTION OF RISK. I knowingly and freely assume all risks of participation, both known and unknown, including risks arising from the actions or inactions of coaches, other participants, facility operators, and equipment, to the fullest extent permitted by applicable law.',
      '',
      '5. WAIVER AND RELEASE. To the fullest extent permitted by Michigan law, I release, waive, and discharge LevelCoach Training, its owners, officers, employees, contractors, and agents, and the coaches and organizations providing services through the platform, from any and all claims, demands, causes of action, and liabilities arising out of or related to my participation in training activities, including claims based on ordinary negligence. This release does not extend to gross negligence, willful misconduct, or any liability that cannot be waived under applicable law.',
      '',
      '6. INDEMNIFICATION. I agree to indemnify and hold harmless the released parties from claims brought by third parties arising out of my own negligent or intentional acts or omissions during training activities, to the extent permitted by law.',
      '',
      '7. FACILITY AND EQUIPMENT RULES. I agree to follow coach instructions, posted facility rules, equipment-use guidelines, and LevelCoach safety policies at all times. I am responsible for using appropriate sport-specific protective equipment in serviceable condition, including, where applicable, shin guards, helmets, mouthguards, eyewear, pads, and footwear suited to the playing surface.',
      '',
      '8. WEATHER AND ENVIRONMENTAL CONDITIONS. I understand that outdoor sessions may be affected by heat, cold, lightning, air quality, and surface conditions, and that coaches are expected to modify or cancel sessions when conditions are unsafe. I agree to follow weather-related instructions from my coach.',
      '',
      '9. INSURANCE. I understand that LevelCoach does not provide medical, health, or accident insurance for participants, and I am responsible for maintaining my own insurance coverage.',
      '',
      '10. MINORS. I understand that this waiver, when applicable to a minor athlete, must be signed by the minor\'s parent or legal guardian through the guardian legal packet. A minor may not sign this waiver on their own behalf.',
      '',
      '11. ACKNOWLEDGEMENT. I have read this document, understand that it affects my legal rights, and sign it voluntarily.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'athlete_medical_emergency',
    role: 'athlete',
    version: '1.1.0',
    title: 'Medical Authorization and Emergency Contact Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. PURPOSE. This document records my emergency contact information obligations and my authorization for emergency medical care in connection with training sessions booked through LevelCoach Training across all sports and performance disciplines offered on the platform.',
      '',
      '2. EMERGENCY CONTACT INFORMATION. I agree to provide and maintain accurate, current emergency contact information in my LevelCoach profile, including at least one reachable emergency contact with name, relationship, and phone number. I understand that coaches rely on this information in an emergency and that out-of-date information may delay care.',
      '',
      '3. AUTHORIZATION FOR EMERGENCY TREATMENT. In the event of an injury or medical emergency during a training session, and if I am unable to communicate my wishes, I authorize the supervising coach or facility staff to contact emergency medical services and to consent on my behalf to reasonable emergency examination, first aid, transport, and treatment by licensed medical professionals until I or my emergency contact can be reached. This authorization is limited to genuine emergencies and does not authorize non-emergency care.',
      '',
      '4. DISCLOSURE OF MEDICAL CONDITIONS. I agree to disclose, in my profile health notes or directly to my coach before a session, any medical condition reasonably relevant to safe participation, including asthma, cardiac conditions, seizure disorders, diabetes, prior concussions, recent injuries or surgeries, and physical limitations. I understand that withholding this information may increase my risk of injury and may limit a coach\'s ability to respond appropriately in an emergency.',
      '',
      '5. CONCUSSION AND HEAD INJURY PROTOCOL. I acknowledge the platform concussion policy: any suspected head injury during a session results in immediate removal from activity; I will not return to training following a suspected concussion until cleared in writing by an appropriate licensed healthcare professional, consistent with Michigan youth sports concussion law where applicable; and coaches are instructed to err on the side of caution.',
      '',
      '6. MEDICATIONS AND ALLERGIES. I agree to disclose allergies (including food, insect, and medication allergies) and any emergency medication I carry, such as an inhaler or epinephrine auto-injector. I understand that coaches are not authorized to administer medication except to assist with self-administered emergency medication or as permitted by law in an emergency.',
      '',
      '7. FINANCIAL RESPONSIBILITY. I understand that I am solely responsible for all costs of medical care, ambulance transport, and related services arising from my participation, and that LevelCoach and its coaches do not provide medical insurance.',
      '',
      '8. HEALTH INFORMATION PRIVACY. Health information I provide is collected for safety and emergency-response purposes only, is visible only to those who need it to deliver or supervise my training, and is handled in accordance with the LevelCoach Privacy Policy. LevelCoach is not a healthcare provider and this information is not maintained as a medical record.',
      '',
      '9. COACHES ARE NOT MEDICAL PROVIDERS. I understand that coaches on the platform are not physicians, athletic trainers, or medical professionals unless separately and expressly credentialed, and that nothing in any training session constitutes medical advice, diagnosis, or treatment.',
      '',
      '10. UPDATES AND REVOCATION. I may update my emergency contact and health information at any time and should do so promptly when it changes. I may revoke this authorization in writing, but I understand that an unrevoked authorization remains in effect for sessions booked through the platform and that revoking it may prevent further booking.',
      '',
      '11. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'athlete_media_release',
    role: 'athlete',
    version: '1.1.0',
    title: 'Photo, Video, and Media Release',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. PURPOSE AND SCOPE. This release governs the capture and use of photographs, video recordings, audio recordings, and other media depicting me ("Media") in connection with training sessions and platform activities across all sports and performance disciplines offered through LevelCoach Training.',
      '',
      '2. TRAINING MEDIA. I consent to my coach capturing Media of me during sessions for instructional purposes, including technique analysis, progress documentation, homework feedback, and session summaries shared with me (and, where applicable, my guardian) through the platform. Training Media is part of my training record and is shared only with me, my linked guardians, my coach, and platform administrators as needed for support and safety.',
      '',
      '3. PROMOTIONAL MEDIA — SEPARATE CONSENT. I understand that use of Media for marketing or promotional purposes — including the LevelCoach website, coach and organization profiles, and social media — is a separate, optional consent that I may grant or decline through my profile settings without affecting my ability to use the platform. Declining promotional use does not limit instructional Training Media used solely within my own training record.',
      '',
      '4. GRANT OF LICENSE. To the extent I have enabled promotional use, I grant LevelCoach Training and my coach or training organization a non-exclusive, royalty-free, worldwide license to use, reproduce, edit, and display the permitted Media for the promotion of training services, in any media format now known or later developed, with or without my name, for as long as the consent remains in effect. No sponsorship or endorsement of any third-party product is implied.',
      '',
      '5. NO COMPENSATION. I understand that I will not receive compensation, royalties, or other consideration for any permitted use of Media, and I waive any right to inspect or approve finished materials that use Media in accordance with this release.',
      '',
      '6. REVOCATION AND REMOVAL. I may revoke promotional media consent at any time through my profile settings or by written notice. Revocation applies prospectively: LevelCoach and the coach or organization will make commercially reasonable efforts to remove Media from sources they control within a reasonable period, but revocation cannot recall Media already distributed, printed, or shared by third parties before the revocation took effect.',
      '',
      '7. THIRD-PARTY PLATFORMS. I understand that Media posted to third-party platforms (such as social networks) is also subject to those platforms\' terms, and that LevelCoach cannot control downstream copying by unrelated third parties.',
      '',
      '8. MINOR ATHLETES. Media consent for a minor athlete may be granted only by the minor\'s parent or legal guardian through the guardian legal packet and guardian-controlled settings. Coaches are instructed never to capture or post Media of a minor athlete without verified guardian consent on file, and promotional Media of minors must not include the minor\'s full name, school, or location details.',
      '',
      '9. OTHER PARTICIPANTS. I agree not to capture or publish Media of other athletes, including minors, during sessions except as permitted by platform policy and with appropriate consent.',
      '',
      '10. NO ENDORSEMENT; RELEASE. I release LevelCoach Training, its coaches, and partner organizations from claims arising out of any use of Media that complies with this release, including claims based on right of publicity, privacy, or defamation, to the extent permitted by law.',
      '',
      '11. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'athlete_communication_safety',
    role: 'athlete',
    version: '1.1.0',
    title: 'Communication Policy and Athlete Code of Conduct',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. ON-PLATFORM COMMUNICATION. I agree that all communication with coaches and training organizations regarding scheduling, payments, training plans, and feedback will occur through LevelCoach Training\'s built-in messaging and booking tools. Keeping communication on-platform protects all parties, creates a reviewable record, and is a condition of using the services.',
      '',
      '2. MONITORING AND RETENTION. I understand and consent that platform communications are not private as between me and LevelCoach: messages may be retained, reviewed for safety and policy compliance, and disclosed to guardians of minor participants, to platform safety staff, and to law enforcement where required by law or necessary to address a safety threat.',
      '',
      '3. CODE OF CONDUCT. I agree to treat coaches, athletes, guardians, staff, and facility personnel with respect. I will arrive on time and prepared, follow coach instructions, give honest effort, respect facility property and rules, and represent myself truthfully on the platform, including my age, skill level, and health information.',
      '',
      '4. PROHIBITED CONDUCT. The following conduct is prohibited and may result in immediate suspension or removal: harassment, bullying, intimidation, or discriminatory conduct of any kind; sexual or romantic advances toward any participant; violence or threats; profane or abusive language directed at any person; sharing or requesting sexually explicit content; use or possession of alcohol, illegal drugs, or tobacco at training activities; soliciting or accepting off-platform payment in violation of platform policy; and attempting to obtain a participant\'s private contact information in violation of safety rules.',
      '',
      '5. PROTECTIONS FOR MINOR ATHLETES. I acknowledge the platform youth-safety rules: communications involving a minor athlete are visible to the minor\'s linked parent or legal guardian; coaches must not initiate private, unmonitored contact with a minor athlete on or off the platform; in-person sessions with minors must take place in observable, interruptible settings; and a minor\'s personal contact information is not shared with coaches. These rules are designed to be consistent with the Children\'s Online Privacy Protection Act (COPPA) and recognized youth-sport safeguarding standards.',
      '',
      '6. TRANSPORTATION POLICY. I acknowledge that coaches are prohibited from providing private transportation to or from sessions for athletes, and that athletes and guardians are solely responsible for transportation arrangements.',
      '',
      '7. REPORTING CONCERNS. I agree to promptly report safety concerns, inappropriate communication, boundary violations, injuries, and policy violations using the platform\'s reporting tools or by contacting platform support. Reports are reviewed by platform staff, and retaliation against anyone who makes a good-faith report is prohibited.',
      '',
      '8. EMERGENCIES. The platform\'s messaging tools are not monitored in real time and must not be used to report emergencies. In an emergency I will contact 911 or local emergency services first.',
      '',
      '9. SANCTIONS. I understand that violations of this policy may result in warnings, session cancellation without credit restoration where the violation caused the cancellation, suspension, or permanent removal from the platform, at LevelCoach\'s reasonable discretion, and that LevelCoach may report unlawful conduct to authorities.',
      '',
      '10. POLICY UPDATES. LevelCoach may update this policy as safety practices evolve. Material updates will be communicated through the platform and may require renewed acknowledgement before continued booking.',
      '',
      '11. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'athlete_payment_terms',
    role: 'athlete',
    version: '1.1.0',
    title: 'Payment, Refund, and Cancellation Terms',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. PRICING AND PAYMENT PROCESSING. All prices are stated in United States dollars and are presented before checkout. Payments are processed by Stripe, Inc.; LevelCoach Training does not store full payment card numbers. By completing a purchase I authorize the charge to my selected payment method for the displayed amount, plus any applicable taxes.',
      '',
      '2. SESSION CREDITS. Purchases of training packages are delivered as session credits on my account. Credits are redeemable for sessions with the coach or organization associated with the purchased package, subject to availability, and have no cash value except where required by law. Credits may not be transferred or resold except through platform-supported guardian/athlete relationships.',
      '',
      '3. PLATFORM FEE DISCLOSURE. I understand that LevelCoach retains a platform service fee from each transaction, by default fifteen percent (15%) of the transaction amount, with the remainder paid to the coach and, where applicable, the coach\'s training organization. The fee may vary for particular coaches or organizations. The total price I pay is always the price displayed at checkout; the platform fee is deducted from the amounts paid to the coach and organization, not added to my price.',
      '',
      '4. CANCELLATION AND 24-HOUR CREDIT RESTORATION. I may cancel a booked session through the platform. If I cancel twenty-four (24) hours or more before the scheduled session start time, the session credit is restored to my account automatically. If I cancel less than twenty-four (24) hours before the scheduled start time, the credit may be forfeited, except where the coach or platform elects to restore it or where documented emergency circumstances apply under platform policy.',
      '',
      '5. NO-SHOWS. If I fail to attend a booked session without cancelling, the session may be marked as a no-show and the credit forfeited. Repeated no-shows may result in booking restrictions.',
      '',
      '6. COACH-INITIATED CANCELLATIONS. If a coach cancels or fails to attend a session, my credit is restored in full, regardless of timing. Where a coach cancellation is within the platform\'s short-notice window, the platform may additionally apply goodwill remedies described in platform policy.',
      '',
      '7. RESCHEDULING. Rescheduling requests made twenty-four (24) hours or more before the session start are treated as a cancellation with credit restoration followed by a new booking, and are subject to the coach\'s availability and booking rules (including minimum notice, buffer, and advance-booking limits).',
      '',
      '8. REFUNDS. Refunds to the original payment method, where approved, are processed by platform administrators in accordance with platform policy and applicable law. Refunds may be full or partial and will correspondingly reduce unused session credits. Credits already redeemed for completed sessions are generally not refundable. Nothing in this section limits any non-waivable consumer rights under applicable law.',
      '',
      '9. DISPUTES AND CHARGEBACKS. I agree to contact LevelCoach support to resolve billing issues before initiating a card dispute. If a chargeback is filed on a payment, associated session credits may be frozen while the dispute is investigated, and accounts associated with fraudulent disputes may be suspended.',
      '',
      '10. TAXES. I am responsible for any taxes applicable to my purchases that the platform is required to collect, which will be shown at checkout where applicable.',
      '',
      '11. CHANGES. LevelCoach may update these payment terms prospectively. Changes do not affect the price of purchases already completed. Material changes will be communicated through the platform and may require renewed acknowledgement before further purchases.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'guardian_authority_minor_packet',
    role: 'guardian',
    version: '2.1.0',
    title: 'Parent/Guardian Authority and Minor Athlete Participation Consent',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. CERTIFICATION OF AUTHORITY. I certify under penalty of law that I am the parent, legal guardian, or otherwise legally authorized adult representative of each minor athlete profile I manage on LevelCoach Training, and that I have full legal authority to sign waivers, releases, medical authorizations, media consents, safety acknowledgements, and booking and payment documents on each such minor athlete\'s behalf. I agree to notify LevelCoach promptly if my authority over any linked athlete changes, including through custody changes or court order.',
      '',
      '2. SCOPE AND BINDING TO SPECIFIC ATHLETES. Each consent and signature I provide applies to the specific linked athlete identified in the signing record. Where I manage multiple minor athletes, I understand that required documents are recorded per athlete and that I must complete them for each athlete who will participate.',
      '',
      '3. CONSENT TO PARTICIPATION. I consent to my minor athlete\'s participation in training activities booked through the platform across all applicable sports and performance disciplines — including, without limitation, soccer, basketball, football, baseball, softball, volleyball, tennis, lacrosse, hockey, golf, track and field, swimming, and speed, agility, strength, and general athletic performance training — with coaches and organizations I select.',
      '',
      '4. ASSUMPTION OF RISK, WAIVER, AND RELEASE ON BEHALF OF A MINOR. I understand that athletic training involves inherent risks, including the risk of serious injury, permanent disability, or death. On my own behalf and, to the fullest extent permitted by Michigan law, on behalf of the minor athlete, I assume these risks and release LevelCoach Training, its owners, officers, employees, contractors, and agents, and the coaches and organizations providing services through the platform, from claims arising out of the minor\'s participation, including claims based on ordinary negligence. This release does not extend to gross negligence, willful misconduct, or liability that cannot be waived. I acknowledge that the enforceability of a pre-injury parental waiver may be limited by Michigan law, and I agree that any portion found unenforceable is severable and that the remainder of this consent, including the assumption of risk, remains in effect.',
      '',
      '5. COPPA AND CHILDREN\'S PRIVACY CONSENT. I understand that the minor athlete does not hold their own platform account; the athlete is represented through my guardian account. I provide verifiable parental consent, consistent with the Children\'s Online Privacy Protection Act (COPPA), to the collection and use of the minor\'s personal information — including name, date of birth, sport and skill information, health and emergency information I choose to provide, and training-progress records — solely for the purposes described in the Privacy Policy. I may review the minor\'s information, request deletion, and withdraw consent, in which case the minor\'s participation will end.',
      '',
      '6. SUPERVISION AND ACCOUNT RESPONSIBILITY. I am responsible for all bookings, payments, communications, and consents made through my account on behalf of linked minor athletes, and for supervising the minor\'s use of any platform features made available to them.',
      '',
      '7. COMMUNICATIONS OVERSIGHT. I acknowledge that platform communications involving my minor athlete are visible to me, that coaches are prohibited from private unmonitored contact with minors, and that I will report any boundary or safety concern through the platform\'s reporting tools.',
      '',
      '8. BOOKING AND APPROVAL. I acknowledge that sessions for a minor athlete may be booked only by, or with the approval of, a linked guardian whose required legal documents are current, and that the platform enforces this requirement at booking time.',
      '',
      '9. SAFETY POLICIES. I acknowledge the platform youth protection, code of conduct, no-private-transportation, injury and concussion reporting, and incident reporting policies, and agree to ensure my minor athlete understands and follows them.',
      '',
      '10. REVOCATION. I may revoke my consents prospectively at any time by written notice or through account settings; revocation ends the minor\'s ability to participate but does not affect obligations already incurred.',
      '',
      '11. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'guardian_medical_media_safety',
    role: 'guardian',
    version: '2.1.0',
    title: 'Minor Athlete Medical Authorization, Media Consent, and Safety Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. PURPOSE. This document records my medical, emergency, media, and safety consents for each minor athlete I manage on LevelCoach Training, across all sports and performance disciplines offered on the platform. Each consent applies to the specific linked athlete identified in the signing record.',
      '',
      '2. EMERGENCY CONTACT INFORMATION. I agree to provide and keep current accurate emergency contact information for each minor athlete, including at least one reachable contact with name, relationship, and phone number. I understand that coaches rely on this information in an emergency.',
      '',
      '3. EMERGENCY MEDICAL AUTHORIZATION. If the minor athlete is injured or experiences a medical emergency during a session and I cannot be reached immediately, I authorize the supervising coach or facility staff to contact emergency medical services and to consent on my behalf to reasonable emergency examination, first aid, transport, and treatment of the minor by licensed medical professionals until I can be reached. This authorization is limited to genuine emergencies. I will be contacted as soon as practicable.',
      '',
      '4. HEALTH DISCLOSURES. I agree to disclose, in the athlete\'s profile health notes or directly to the coach, any condition reasonably relevant to the minor\'s safe participation — including asthma, cardiac conditions, seizure disorders, diabetes, allergies, prior concussions, recent injuries or surgeries, and physical limitations — and any emergency medication the minor carries, such as an inhaler or epinephrine auto-injector. Coaches may assist with self-administered emergency medication but are not authorized to administer medication except as permitted by law in an emergency.',
      '',
      '5. CONCUSSION AND HEAD INJURY PROTOCOL FOR MINORS. I acknowledge the platform concussion policy, consistent with Michigan youth sports concussion law: a minor with a suspected concussion or head injury is removed from activity immediately, I will be notified, and the minor may not return to training until cleared in writing by an appropriate licensed healthcare professional.',
      '',
      '6. MEDIA CONSENT FOR MINORS. I control all media consents for my minor athlete through my guardian settings. I may permit instructional training media (technique video and progress documentation shared only within the athlete\'s training record) and may separately permit or decline promotional media use. Promotional use of a minor\'s media requires my explicit opt-in, must never include the minor\'s full name, school, or location details, and may be revoked prospectively at any time. Declining promotional media does not affect the minor\'s ability to participate.',
      '',
      '7. SAFETY POLICY ACKNOWLEDGEMENT. I acknowledge the platform youth protection rules: observable and interruptible training environments for minors; prohibition on private, unmonitored coach-minor contact on or off the platform; prohibition on coaches providing private transportation; mandatory injury and incident reporting; and the athlete and coach codes of conduct.',
      '',
      '8. COMMUNICATION MONITORING. I consent to and acknowledge that all platform communications involving my minor athlete are visible to me, are retained, and may be reviewed by platform safety staff for compliance and safety purposes, consistent with the Privacy Policy and the Children\'s Online Privacy Protection Act (COPPA).',
      '',
      '9. FINANCIAL RESPONSIBILITY. I am responsible for all costs of medical care, ambulance transport, and related services for the minor arising from participation. LevelCoach and its coaches do not provide medical insurance.',
      '',
      '10. PARTICIPATION GATE. I understand that a minor athlete may not be booked into sessions until the required guardian legal documents for that athlete are current, and that expired or superseded documents must be re-signed before further booking.',
      '',
      '11. UPDATES AND REVOCATION. I may update health information, emergency contacts, and media settings at any time, and may revoke these consents prospectively in writing or through account settings; revocation ends the minor\'s participation.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'guardian_payment_booking_consent',
    role: 'guardian',
    version: '1.1.0',
    title: 'Guardian Payment Authority and Booking Approval Consent',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. GUARDIAN AS PAYING PARTY. I acknowledge that, as the parent or legal guardian, I am the contracting and paying party for all purchases and bookings made for minor athletes linked to my account on LevelCoach Training. Minor athletes cannot make purchases or enter payment obligations on the platform.',
      '',
      '2. PAYMENT AUTHORIZATION. I authorize charges to my selected payment method for purchases I complete through the platform at the prices displayed at checkout, in United States dollars, processed by Stripe, Inc. I represent that I am authorized to use the payment methods I provide.',
      '',
      '3. PLATFORM FEE DISCLOSURE. I understand that LevelCoach retains a platform service fee from each transaction, by default fifteen percent (15%) of the transaction amount, with the remainder paid to the coach and, where applicable, the coach\'s training organization. The fee is deducted from amounts paid to the coach and organization; the price I pay is always the price displayed at checkout.',
      '',
      '4. SESSION CREDITS. Package purchases are delivered as session credits usable for the linked athlete with the associated coach or organization, subject to availability and booking rules. Credits have no cash value except where required by law.',
      '',
      '5. BOOKING APPROVAL FOR MINORS. I acknowledge that sessions for a minor athlete may be booked only by me or with my approval as a linked guardian with current legal documents, and that the platform enforces this gate at booking time. Booking requests initiated for a minor remain pending until guardian approval where the platform requires it.',
      '',
      '6. PERMISSION SETTINGS. I understand that I control per-athlete permission settings — including whether the athlete may request bookings (can_book), whether payments may be initiated in connection with the athlete\'s activity (can_pay), and whether the athlete may use messaging (can_message) — and that these settings are enforced by the platform. I am responsible for reviewing and maintaining these settings.',
      '',
      '7. CANCELLATION AND 24-HOUR CREDIT RESTORATION. I acknowledge the platform cancellation policy: cancellations made twenty-four (24) hours or more before a session\'s scheduled start restore the session credit automatically; cancellations made less than twenty-four (24) hours before the start may forfeit the credit, except where the coach or platform elects to restore it or documented emergency circumstances apply. If a coach cancels or fails to attend, the credit is restored in full.',
      '',
      '8. NO-SHOWS AND LATE ARRIVALS FOR MINORS. I am responsible for the minor athlete\'s timely arrival at sessions. Sessions missed without cancellation may be marked as no-shows with credit forfeiture under platform policy.',
      '',
      '9. REFUNDS AND DISPUTES. Approved refunds are processed by platform administrators to the original payment method and correspondingly reduce unused credits. I agree to contact LevelCoach support to resolve billing issues before initiating a card dispute; credits associated with a disputed payment may be frozen during investigation.',
      '',
      '10. RECEIPTS AND RECORDS. Purchase records, receipts, and signed documents are available in my account. I consent to electronic delivery of receipts and payment-related notices.',
      '',
      '11. CHANGES. LevelCoach may update these terms prospectively; changes do not affect completed purchases, and material changes will be communicated through the platform and may require renewed acknowledgement before further purchases.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'coach_independent_contractor_packet',
    role: 'coach',
    version: '2.1.0',
    title: 'Coach Independent Contractor Agreement and Payout Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. INDEPENDENT CONTRACTOR STATUS. I acknowledge and agree that my relationship with LevelCoach Training is that of an independent contractor using a marketplace platform, and not employment, partnership, joint venture, or agency. I control the manner and means of delivering my coaching services, set my availability, and may decline bookings, subject to platform policies. Nothing in this agreement entitles me to wages, benefits, workers\' compensation, or unemployment insurance from LevelCoach.',
      '',
      '2. TAXES. I am solely responsible for all federal, state, and local taxes on amounts I earn through the platform, including self-employment taxes. I agree to provide accurate taxpayer information through Stripe as required for tax reporting (including IRS Form 1099 series where applicable), and I understand payouts may be suspended if required tax information is missing or inaccurate.',
      '',
      '3. CREDENTIALS, INSURANCE, AND COMPLIANCE. I represent that I possess the skills, certifications, licenses, and permissions required to provide the training services I list, across each sport and performance discipline I offer; that the credentials I present on the platform are accurate; and that I will maintain any insurance required by law or by the facilities I use. I will comply with all applicable laws in providing services.',
      '',
      '4. MARKETPLACE RULES AND NON-CIRCUMVENTION. I agree that all bookings and payments for clients introduced through the platform will be conducted on-platform unless LevelCoach expressly approves otherwise in writing. I will not solicit platform clients to transact off-platform, harvest contact information, or accept off-platform payment for platform-originated training. I may continue independent relationships that verifiably pre-date the platform introduction.',
      '',
      '5. PAYOUT ACKNOWLEDGEMENT AND PLATFORM FEE DISCLOSURE. I understand and agree to the platform compensation structure: LevelCoach retains a platform service fee of fifteen percent (15%) of each transaction by default; the platform may agree with me on a different percentage, which will be reflected in my coach record before it applies. For training delivered through an affiliated organization with a payout rule in place, the default revenue split is sixty percent (60%) to the coach, twenty-five percent (25%) to the organization, and fifteen percent (15%) to the platform; organization-specific splits may differ but will always be disclosed to me and will always total one hundred percent (100%). The price charged to the client is set by the applicable platform pricing package.',
      '',
      '6. STRIPE CONNECT. Payouts are made exclusively through Stripe Connect. I must complete Stripe onboarding, satisfy Stripe\'s verification requirements, and keep my account in good standing before I can be published or receive payouts. I agree to Stripe\'s connected-account terms.',
      '',
      '7. REFUNDS, DISPUTES, AND PAYOUT REVERSALS. I acknowledge that client refunds approved under platform policy, and chargebacks resolved against the platform, will reverse my associated payout proportionally, and that LevelCoach may offset reversed amounts against future payouts. I agree to cooperate promptly and truthfully in refund and dispute investigations.',
      '',
      '8. PRICING AND PACKAGES. Client-facing prices are defined by platform pricing packages administered through the platform. I will not charge platform clients amounts outside the platform for platform-originated sessions.',
      '',
      '9. PUBLISH REQUIREMENTS. I understand my profile will not be published to the marketplace until my required legal documents are signed, my email is verified, my profile is complete, and my Stripe Connect account is ready.',
      '',
      '10. RECORDS. I consent to the platform retaining records of my sessions, communications, payouts, and signed documents as described in the Privacy Policy, and to the issuance of payout and tax documentation through Stripe.',
      '',
      '11. TERM AND TERMINATION. Either party may end this relationship at any time. Obligations relating to completed transactions, non-circumvention for platform-originated clients, indemnification, and records survive termination. LevelCoach may suspend or remove my listing for policy violations or safety concerns.',
      '',
      '12. INDEMNIFICATION. I agree to indemnify LevelCoach against third-party claims arising from my negligent or intentional acts or omissions in providing coaching services, to the extent permitted by law.',
      '',
      '13. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'coach_safeguarding_boundaries_packet',
    role: 'coach',
    version: '2.1.0',
    title: 'Coach Safeguarding, Youth Protection, Background Check Consent, and Code of Conduct',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. COMMITMENT TO ATHLETE SAFETY. As a coach on LevelCoach Training, I accept personal responsibility for the physical and emotional safety of every athlete I train, in every sport and performance discipline I offer, and I agree to the safeguarding standards in this document as a condition of listing and remaining on the platform.',
      '',
      '2. BACKGROUND CHECK CONSENT. I consent to LevelCoach, directly or through a consumer reporting agency, obtaining and periodically refreshing background screening about me — which may include criminal history, sex-offender registry checks, and verification of identity and credentials — where enabled by the platform and permitted by law. I understand I will receive any disclosures and authorization forms required by the Fair Credit Reporting Act (FCRA) and applicable state law before such screening, and that adverse findings may result in denial, suspension, or removal, subject to any legally required pre-adverse-action process.',
      '',
      '3. YOUTH PROTECTION STANDARDS. I agree to the platform\'s minor-athlete protections: training environments for minors must be observable and interruptible; I will not be alone with a minor athlete in a private, unobservable setting; sessions occur at appropriate facilities, never at private residences without a guardian present; and a linked parent or legal guardian must be able to attend and observe any session with a minor.',
      '',
      '4. PROFESSIONAL BOUNDARIES. I will maintain strictly professional relationships with athletes and their families. Romantic or sexual contact or communication with any minor is absolutely prohibited and will be reported to authorities; romantic relationships with adult athletes I actively train are prohibited while the training relationship exists. I will avoid gifts, favoritism, secrecy, and any grooming-pattern behavior, and I will respect each athlete\'s physical boundaries, using physical contact only when instructionally necessary, appropriate, and consented to.',
      '',
      '5. TRANSPORTATION PROHIBITION. I will not provide private transportation to or from sessions for any athlete. Transportation is the responsibility of athletes and their guardians.',
      '',
      '6. COMMUNICATION RULES WITH MINORS. All my communication with minor athletes will occur through platform channels visible to the athlete\'s guardian. I will not initiate private contact with a minor by phone, text, email, social media, gaming platforms, or any other channel, and I will redirect any such contact initiated by a minor back to monitored platform channels and notify the guardian.',
      '',
      '7. MANDATORY REPORTING. I understand that Michigan law designates certain persons as mandated reporters of suspected child abuse or neglect, and regardless of my formal status I agree to immediately report reasonable suspicions of abuse or neglect to the Michigan Department of Health and Human Services and, where applicable, law enforcement, and to notify platform safety staff. I will also report safety incidents, injuries, and boundary concerns through the platform\'s reporting tools.',
      '',
      '8. CODE OF CONDUCT. I will model respectful behavior; never use abusive, demeaning, or discriminatory language; never harass, haze, bully, or retaliate; coach within my qualifications; follow concussion and injury protocols, including immediate removal from activity for suspected head injuries and written medical clearance before return; and follow facility rules and platform policies.',
      '',
      '9. SUBSTANCES. I will not use, possess, or be under the influence of alcohol, illegal drugs, or recreational cannabis during sessions, and I will not use tobacco or vaping products in the presence of minor athletes. I will never provide any such substance to an athlete.',
      '',
      '10. VIOLATIONS AND SANCTIONS. I understand that suspected violations may result in immediate interim suspension while investigated, and confirmed violations may result in permanent removal, notification to guardians and organizations, and referral to law enforcement. I agree to cooperate fully with platform investigations.',
      '',
      '11. ONGOING OBLIGATIONS. I will promptly disclose to LevelCoach any arrest, charge, conviction, or registry listing that occurs after my onboarding and that is relevant to athlete safety, and I will keep my certifications and safety training current where required by the platform.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'coach_communication_policy',
    role: 'coach',
    version: '1.1.0',
    title: 'Coach Communication Policy Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. ON-PLATFORM REQUIREMENT. I agree to conduct all communication with platform clients — athletes, parents, and guardians — through LevelCoach Training\'s built-in messaging and booking tools for all matters relating to scheduling, payments, training plans, assessments, homework, and feedback. On-platform communication protects athletes, families, and me by creating a consistent, reviewable record.',
      '',
      '2. MONITORING AND RETENTION. I understand and consent that platform communications are retained and may be reviewed by platform safety and support staff for policy compliance, safety, and dispute resolution, and may be disclosed to guardians of minor participants and, where required by law or necessary to address a safety threat, to law enforcement.',
      '',
      '3. COMMUNICATIONS INVOLVING MINORS. All communication with a minor athlete must occur in channels visible to the minor\'s linked guardian. I will not request, store, or use a minor\'s personal contact information, and I will not communicate with a minor through any off-platform channel, including text, phone, email, social media, or gaming platforms. If a minor contacts me off-platform, I will not continue the exchange, will redirect to platform channels, and will notify the guardian and, where appropriate, platform safety staff.',
      '',
      '4. PROFESSIONAL STANDARDS. My communications will be professional, sport-appropriate, and respectful at all times. I will keep feedback constructive and age-appropriate, avoid sarcasm and personal criticism with younger athletes, and direct sensitive topics — health concerns, payment issues, complaints — through the appropriate platform workflows.',
      '',
      '5. PROHIBITED CONTENT. I will not send or request sexually explicit content, romantic communication, harassment, threats, discriminatory remarks, or solicitations to transact off-platform. I will not share another client\'s personal information in any communication.',
      '',
      '6. SOCIAL MEDIA BOUNDARIES. I will not initiate private social-media connections with minor athletes, and I will route any public social-media interactions with platform clients that involve scheduling, payment, or training matters back to the platform. Promotional posts featuring athletes require valid media consent on file as described in the media release policies.',
      '',
      '7. RESPONSIVENESS. I will respond to booking requests and client messages within a commercially reasonable time, and I will use the platform\'s scheduling tools — not informal messages — to confirm, change, or cancel sessions so that credits, notifications, and records remain correct.',
      '',
      '8. SCHEDULING CHANGES. Any cancellation or rescheduling I initiate must be performed through the platform so the client\'s session credit is restored according to policy. I will give as much notice as possible and understand that repeated short-notice coach cancellations may affect my marketplace standing.',
      '',
      '9. EMERGENCIES AND INCIDENTS. Platform messaging is not for emergencies; in an emergency I will contact 911 first, then the athlete\'s emergency contact, then platform safety staff. I will report injuries, safety incidents, and boundary concerns through the platform\'s incident reporting tools promptly after they occur.',
      '',
      '10. SANCTIONS. I understand that violations of this policy may result in warnings, suspension, unpublishing of my profile, or permanent removal from the platform, and that serious violations involving minors will be escalated under the safeguarding policy, including reporting to authorities where appropriate.',
      '',
      '11. POLICY UPDATES. LevelCoach may update this policy as safety and communication practices evolve; material updates will be communicated through the platform and may require renewed acknowledgement to continue accepting bookings.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'organization_service_authority_packet',
    role: 'organization',
    version: '2.1.0',
    title: 'Organization Service Agreement, Signing Authority, and Payout Split Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. SIGNING AUTHORITY. I certify that I am an owner, officer, or duly authorized representative of the organization identified in this signing record, with full legal authority to bind the organization to LevelCoach Training\'s platform terms, marketplace rules, payment and payout policies, data-handling obligations, and the commitments in this packet. The organization will promptly notify LevelCoach if my authority changes.',
      '',
      '2. ORGANIZATION SERVICES. The organization may use the platform to maintain an organization profile, manage a roster of affiliated coaches across any sports and performance disciplines it offers, receive bookings and payments for organization-affiliated training, configure payout arrangements with its coaches, and administer organization members with role-based access. The organization is responsible for all actions taken by its authorized members within the organization portal.',
      '',
      '3. ROSTER AND COACH MANAGEMENT. The organization is responsible for the accuracy of its coach roster and for ensuring that each affiliated coach has accepted the affiliation, maintains the credentials the organization represents, and complies with platform policies, including the coach safeguarding and communication policies. The organization will promptly suspend or remove coaches who no longer meet its standards or the platform\'s.',
      '',
      '4. PAYOUT SPLIT ACKNOWLEDGEMENT. The organization understands and agrees to the platform compensation structure for organization-affiliated training: by default, sixty percent (60%) of each transaction is paid to the coach, twenty-five percent (25%) to the organization, and fifteen percent (15%) is retained by the platform as its service fee. The organization may configure different splits for individual coach affiliations through platform payout rules, subject to platform validation that each split totals exactly one hundred percent (100%) and to disclosure to the affected coach before the rule takes effect. Changes to payout rules apply prospectively only and are recorded in the platform audit log.',
      '',
      '5. STRIPE CONNECT. Organization payouts are made exclusively through Stripe Connect. The organization must complete Stripe onboarding, satisfy verification requirements, and keep its connected account in good standing before its profile is published or payouts are made. The organization agrees to Stripe\'s connected-account terms and is responsible for accurate tax information.',
      '',
      '6. REFUNDS, DISPUTES, AND REVERSALS. The organization acknowledges that client refunds approved under platform policy, and chargebacks resolved against the platform, reverse the organization\'s associated payout proportionally, and that LevelCoach may offset reversed amounts against future payouts. The organization agrees to cooperate promptly in refund and dispute investigations involving its coaches or facilities.',
      '',
      '7. NON-CIRCUMVENTION. All bookings and payments for clients introduced through the platform must be conducted on-platform unless LevelCoach expressly approves otherwise in writing. The organization will not solicit platform clients to transact off-platform and will not permit its coaches to do so for platform-originated clients.',
      '',
      '8. BRAND LICENSE. The organization grants LevelCoach a non-exclusive, royalty-free license to display the organization\'s name, logo, and profile content on the platform and in platform marketing that identifies organizations using the service, for as long as the organization maintains an active profile. The organization represents it has the rights to the branding it provides.',
      '',
      '9. PUBLISH REQUIREMENTS. The organization\'s profile will not be published until its required legal documents are signed by an authorized representative and its Stripe Connect account is ready.',
      '',
      '10. COMPLIANCE WITH LAW. The organization will comply with all laws applicable to its operations, including youth-sports safety requirements, employment and contractor classification laws for its own personnel, facility safety codes, and data protection laws.',
      '',
      '11. TERM, SUSPENSION, AND TERMINATION. Either party may terminate the organization\'s participation at any time, subject to completion of obligations on existing bookings. LevelCoach may suspend the organization\'s profile or payouts for policy violations, safety concerns, or legal compliance issues. Payment, audit, indemnification, and data obligations survive termination.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
  {
    template_key: 'organization_roster_privacy_safety_packet',
    role: 'organization',
    version: '2.1.0',
    title: 'Organization Roster Responsibility, Privacy, Facility, and Safety Obligations',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      '1. ROSTER ACCURACY AND AUTHORITY. The organization certifies that every coach listed on its platform roster has agreed to the affiliation, that public titles, credentials, and sport offerings attributed to its coaches are accurate, and that the organization has authority to manage the bookings and payout arrangements it configures for its roster. The organization will keep its roster current, removing coaches promptly when affiliations end.',
      '',
      '2. COACH COMPLIANCE. The organization will verify that each affiliated coach maintains the certifications, licenses, and insurance the organization represents to clients; has completed the platform\'s required coach legal documents; and complies with the platform safeguarding, youth protection, communication, and conduct policies. The organization will not knowingly retain on its roster any coach who presents a safety risk to athletes.',
      '',
      '3. FACILITY SAFETY. For sessions conducted at facilities the organization owns, leases, or controls, the organization is responsible for maintaining the facility in reasonably safe condition, complying with applicable building, fire, and safety codes, maintaining appropriate emergency equipment and procedures, and ensuring playing surfaces and equipment are suitable for the sports and performance disciplines offered.',
      '',
      '4. INSURANCE ATTESTATION. The organization represents that it maintains commercially reasonable general liability insurance appropriate to its operations and facilities, and any coverage required by law, and will provide evidence of coverage to LevelCoach upon reasonable request.',
      '',
      '5. YOUTH PROTECTION OBLIGATIONS. The organization adopts the platform\'s youth protection standards for all organization-affiliated activity: observable and interruptible training environments for minors; no private, unmonitored coach-minor contact; no private transportation of athletes by coaches; guardian access to observe sessions involving their minor athletes; and immediate removal from activity and guardian notification for suspected head injuries, with written medical clearance before return to training.',
      '',
      '6. PRIVACY AND DATA PROTECTION. The organization will access and use athlete, guardian, and coach personal data available through the organization portal solely to deliver and administer training services through the platform. The organization will limit access to members with a need to know, protect credentials, and not export, sell, or disclose platform personal data to third parties except as required by law. Data relating to minor athletes receives heightened protection consistent with the Children\'s Online Privacy Protection Act (COPPA); the organization will not contact minor athletes directly outside guardian-visible platform channels and will not build marketing lists from minors\' data.',
      '',
      '7. DATA USE RESTRICTIONS AND NON-SOLICITATION. The organization will not use platform-derived contact information to solicit clients to off-platform transactions, and will direct all platform-originated bookings and payments through the platform consistent with its service agreement.',
      '',
      '8. INCIDENT REPORTING. The organization will report injuries, safety incidents, safeguarding concerns, and suspected policy violations involving its coaches, members, facilities, or affiliated sessions through the platform\'s reporting tools promptly, and in any event within seventy-two (72) hours of becoming aware, and will report suspected child abuse or neglect to the Michigan Department of Health and Human Services and law enforcement as required by law.',
      '',
      '9. COMMUNICATION OVERSIGHT. The organization acknowledges that platform communications involving its roster are retained and may be reviewed by platform safety staff, and it will ensure organization members use platform channels for client communications relating to scheduling, payment, and training.',
      '',
      '10. AUDIT AND COOPERATION. The organization will cooperate with LevelCoach reviews of roster accuracy, safety compliance, and data handling, and will promptly remediate identified deficiencies. Material failures may result in suspension of the organization profile or payouts.',
      '',
      '11. SANCTIONS. Violations of this packet may result in warnings, unpublishing, suspension of payouts, removal from the platform, and notification of affected clients, in LevelCoach\'s reasonable discretion, in addition to any remedies available at law.',
      '',
      '12. GOVERNING LAW AND SEVERABILITY. ' + GOVERNING_LAW,
    ].join('\n'),
  },
];

export function templateIdentity(template) {
  return [
    template.template_key,
    template.role,
    template.version,
    template.title,
    template.body,
    template.jurisdiction || '',
  ].join('\n');
}
