export const LEGAL_TEMPLATE_SEED = [
  {
    template_key: 'platform_terms_privacy_ack',
    role: 'athlete',
    version: '2026.06.07',
    title: 'Platform Terms, Privacy, and Electronic Records Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I acknowledge the current LevelCoach Training Terms of Service and Privacy Policy. I consent to electronic records and electronic signatures for account, booking, payment, safety, messaging, and training-related documents.',
      '',
      'I understand that LevelCoach Training is a sports training marketplace and operations platform. Coaches and organizations may provide training services subject to platform rules, applicable law, and the required safety policies.',
    ].join('\n'),
  },
  {
    template_key: 'athlete_participation_waiver',
    role: 'athlete',
    version: '2026.06.07',
    title: 'Athlete Participation, Assumption of Risk, Waiver, Release, and Indemnification',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I understand that athletic training involves inherent risks, including physical exertion, contact with equipment or surfaces, weather conditions, and risk of injury. I confirm that I am medically able to participate or will consult a medical professional before participating.',
      '',
      'I agree to follow coach instructions, facility rules, and LevelCoach safety policies. I acknowledge cancellation, refund, no-show, rescheduling, messaging, conduct, and no off-platform contact policies.',
    ].join('\n'),
  },
  {
    template_key: 'athlete_health_media_safety',
    role: 'athlete',
    version: '2026.06.07',
    title: 'Health, Emergency, Media, Messaging, and Safety Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I agree to provide accurate emergency contact and health information where requested. I acknowledge injury, concussion, incident reporting, messaging monitoring, code of conduct, no private transportation, and no unsupervised off-platform contact policies.',
      '',
      'I understand that optional photo/video/media consent may be revoked where legally appropriate, but required safety and operational communications cannot be opted out of while using the services.',
    ].join('\n'),
  },
  {
    template_key: 'guardian_authority_minor_packet',
    role: 'guardian',
    version: '2026.06.07',
    title: 'Parent/Guardian Authority and Minor Athlete Legal Packet',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I certify that I am the parent or legal guardian, or otherwise legally authorized adult, for the minor athlete profile(s) I manage. I am authorized to sign waivers, releases, emergency medical authorizations, safety acknowledgements, and booking/payment documents on the minor athlete\'s behalf.',
      '',
      'I acknowledge the current Terms of Service, Privacy Policy, electronic records consent, messaging monitoring, no private transportation, youth protection, code of conduct, cancellation, refund, no-show, and rescheduling policies.',
    ].join('\n'),
  },
  {
    template_key: 'guardian_medical_media_safety',
    role: 'guardian',
    version: '2026.06.07',
    title: 'Minor Athlete Medical Authorization, Media, and Safety Consent',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I agree to provide accurate emergency contact and health information for minor athlete profiles I manage. I acknowledge injury, concussion, incident reporting, safe messaging, monitored communications, and optional media consent controls.',
      '',
      'I understand that a minor athlete may not book, match, or participate through LevelCoach until required parent/guardian legal documents are current.',
    ].join('\n'),
  },
  {
    template_key: 'coach_independent_contractor_packet',
    role: 'coach',
    version: '2026.06.07',
    title: 'Coach Independent Contractor, Marketplace, and Payout Acknowledgement',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I acknowledge that my relationship with LevelCoach is intended to be an independent contractor/marketplace relationship and not employment. I am responsible for taxes, credentials, insurance, professional conduct, and compliance with applicable law.',
      '',
      'I acknowledge Stripe Connect payout requirements, tax information obligations, refund/dispute cooperation, and that all paid bookings must remain on-platform unless LevelCoach expressly approves otherwise in writing.',
    ].join('\n'),
  },
  {
    template_key: 'coach_safeguarding_boundaries_packet',
    role: 'coach',
    version: '2026.06.07',
    title: 'Coach Safeguarding, Youth Protection, Conduct, and Background Authorization',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I agree to follow LevelCoach safeguarding, youth protection, professional boundaries, no private transportation, no unsupervised off-platform contact, incident reporting, injury reporting, messaging, and code of conduct policies.',
      '',
      'I consent to credential, insurance, certification, license, CPR/first aid, and background-check related review where enabled by LevelCoach and permitted by law.',
    ].join('\n'),
  },
  {
    template_key: 'organization_service_authority_packet',
    role: 'organization',
    version: '2026.06.07',
    title: 'Organization Service Agreement and Signing Authority Attestation',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'I certify that I am authorized to bind the organization to LevelCoach platform terms, marketplace rules, booking/payment policies, data handling obligations, and organization portal responsibilities.',
      '',
      'I acknowledge organization Stripe Connect payout requirements, refund/dispute responsibilities, coach roster responsibilities, brand/logo license, and non-circumvention/no off-platform payment policies.',
    ].join('\n'),
  },
  {
    template_key: 'organization_roster_privacy_safety_packet',
    role: 'organization',
    version: '2026.06.07',
    title: 'Organization Roster, Privacy, Facility, and Safety Responsibility',
    jurisdiction: 'Michigan, United States',
    required: true,
    body: [
      'Attorney review required before production use.',
      '',
      'The organization is responsible for the accuracy and authority of its listed coaches, facility information, branding, insurance/certification attestations, and organization-managed training operations.',
      '',
      'The organization acknowledges youth protection, incident reporting, athlete/parent/coach data privacy, coach compliance, and safe communication obligations.',
    ].join('\n'),
  },
];

export function templateIdentity(template) {
  return [
    template.template_key,
    template.role,
    template.version,
    template.title,
    template.body,
    template.jurisdiction || '',
  ].join('\n');
}
